# trunk-ignore-all(trivy/KSV116)
# trunk-ignore(checkov/CKV_K8S_21)
apiVersion: v1
kind: Service
metadata:
  name: ums-api-svc
spec:
  ports:
    - name: ums-api-port
      protocol: TCP
      port: 80
      # TODO: Use nginx for deployment.
      targetPort: 8081 # Gunicorn PORT
      # targetPort: 81 # Nginx PORT
  type: NodePort
  selector:
    app-ums: 'true'
